title: Hello, world! I'm Gökhan Şişman
description: > # this means to ignore newlines until "baseurl:"
  Gökhan Şişman
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gökhan Şişman # add your name
author-img: gokhansisman.jpg # add your photo
about-author: I am a web developer focusing on back-end development. Always follow my dreams. # add description
social-twitter: # add your Twitter handle
social-facebook: gokhans1sman # add your Facebook handle
social-github: gokhansisman # add your Github handle
social-linkedin: g%C3%B6khan-%C5%9Fi%C5%9Fman-784ba8159/ # add your Linkedin handle
social-email: gokhansisman97@gmail.com # add your Email address

# Disqus
discus-identifier: mr-sisman # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
